name: CI

on:
  push:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - uses: Bancar/uala-ftp-deploy-action@master
          ftp-server: ec2-50-16-104-244.compute-1.amazonaws.com
          ftp-path: /home/ec2-user/websitetest/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ssh-key: ${{ secrets.FTP_SSH_KEY }}

          


  
