name: CI

on:
  push:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
  
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: asarabia-uala/ftp-action
          ref: master
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }} 
          path: .github/actions/ftp-action

      - name: deploy file
        uses: ./.github/actions/ftp-action
        with:
          ftp-server: ec2-50-16-104-244.compute-1.amazonaws.com
          ftp-path: /home/ec2-user/websitetest/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-ssh-key: ${{ secrets.FTP_SSH_KEY }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          action-status: ${{ job.status }}